### ISSUE TITLE
Add functionality for storing amount of time users spends tagging images

### ISSUE THREAD

**Issue by Matmorcat** [UNCG-CSE/Poststorm_Imagery#158]
- [x] Send it as a parameter (running total of seconds) from dashboard front-end @ShahNafisRafique 
- [x] Retrieve it on the back-end and store it as a non-comparing tag @Matmorcat

**Comment by ShahNafisRafique** [comment]
So I get the time that the image is sent to the user and the time that the user submits that image. So I basically get how long it took to tag an image on the session that the user submits the image. The time is number of milliseconds since 1 January 1970 00:00:00. Lets call this time, running time

I would like to also know the time that an image was assigned to the user and, if its not redundant, the time that the tags where processed.

With those two times I can say, whats the average time it took to tag an image since it was assigned, whats the time it took to tag an image in 1 session, and when does someone tag their images.

**Comment by Matmorcat** [comment]
Complete
