### ISSUE TITLE
Additional tags

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-CSE/Poststorm_Imagery#185]
In the ideal world there would be an addition option for terrain (Purple tags)  — 'inland'. there are some images where there is no river/marsh/sandy coastline... just random urban/suburban area.

but this is not critical RN... but if it's easy......

**Comment by ShahNafisRafique** [comment]
I added a inland tag option just now however, im unsure how to test it as I dont want to mess with the tagging data. So I will see what matt has to say on how I can test the tag.

**Comment by Matmorcat** [comment]
Depending on how far Evan has gotten, it may be best to just restart tagging as the images he already tagged that were in-land are now not tagged properly

**Comment by Matmorcat** [comment]
Or, @ebgoldstein, if all the images you tagged as terrain N/A are in-land, I can do a manual replace of tags.

**Comment by Matmorcat** [comment]
There are 20 images tagged, 2 skipped, only 1 with terrain N/A, so @ebgoldstein, should I just replace that one image tag with terrain in-land?

**Comment by Matmorcat** [comment]
- `N/A` tags for `developed` & `washover` have been removed as they are not needed and have not been used
- back-end label id for both has been updated and the data in the assigner state has been migrated as such
- Shah added an `inland` option and we tested it to make sure it works, then returned the dashboard to production
- I changed your one image labelled as terrain = `N/A` to terrain = `inland` after looking at the image and confirming it is an inland photo
- Dashboard is now building pages as a production server instead of as a dev server, so some pages may load a tiny bit faster

**Comment by ebgoldstein** [comment]
also anything taged incorrectly from before there was an `inland` should be corrected when tagged by multiple people.

**Comment by Matmorcat** [comment]
It will, but I just changed it manually, since the state is easily readable and there was only 1 :)
