### ISSUE TITLE
Dashboard pop-up window

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-CSE/Poststorm_Imagery#223]
from a colleague: 

> when you submit, you get an unnecessary message that requires extra clicking

can this pop up window (and extra click) be easily removed @ShahNafisRafique ?

**Comment by ShahNafisRafique** [comment]
Yea we if its really needed, I put it in because

1. It serves as a way to say if the image tag data was successfully put in or to show if an error happened
2. I thought it would be pretty weird if the page refreshes without saying anything.

The big reason its there is for displaying any errors so that me and Matt know if theres something we need to fix.

If the concern is that the pop slows down tagging, I dont think it matters too much because of the 250 completely tagged images (as of the 24th) the image that got completed the fastest took 6901 seconds because each image needs multiple people to tag it. So I think improving the tagging time for individuals by 1-2 seconds wont really matter much since we need multiple people to tag.

If you really want we can do it easily though, so its up to you but I recommend we leave it in for the sake of catching errors .

**Comment by ebgoldstein** [comment]
that rationale makes sense to me — happy to leave it in.
